In [ ]:
import numpy as np

Task
----
Write a snippet in python using `numpy` (loops are allowed) performing 1D convolution with fixed kernels, with one input channel and two output channels. Don't use pytorch or any other library.

Change only `#TODO` items

There are two kernels with weights `[1,0,-1]` (channel 0), `[0, 1, 0]` (channel 1).
Code should be as simple as possible, we don’t need full generality (hint: kernels are known). We assume no padding (so the output of each kernel will be shorter by two elements than the input vector).

Compute the gradients as well using mean squared error (sum of squares average). Use batch size=1.

Example
-----
For input `[1, 2, 3, 4, 5]` second kernel should return `[2, 3, 4]`


In [14]:
import numpy as np

# size of input sequence
size = 20

# DON'T CHANGE FROM HERE
# input sequence
np_input = np.random.rand(size)
assert np_input.shape == (size,)

# expected output, loss is calculated against this output
np_expected = np.random.rand(2, size-2)
assert np_expected.shape == (2,size-2)
# DON'T CHANGE TO HERE

#TODO: np_res should be numpy array, result of applying kernels to np_input
np_res = np.random.rand(2, size-2)
KERNEL_1 = np.array([1, 0, -1])
KERNEL_2 = np.array([0, 1, 0])
for i in range(size-2):
    # print(np_input[i:i+3])
    # print(np_input[i:i+3] * KERNEL_1)
    # print(np.sum(np_input[i:i+3] * KERNEL_1))
    # print()
    np_res[0, i] = np.sum(np_input[i:i+3] * KERNEL_1)
    np_res[1, i] = np.sum(np_input[i:i+3] * KERNEL_2)

print(np_res)
#TODO: np_grad should be numpy array, gradients

# c = filter, i = element, x = input
# loss is L = sum_c,i ((y_c,i - y'_c,i)^2) / N
# y_c,i = sum_k (W_c,k * x_i+k)
# dl/dW_c,k = (sum_i ((y_c,i - y'_c,i)^2) / N)' * (W_c,k * x_i+k)' =
# = 2/N * sum_i(y_c,i - y'_c,i) * x_i+k

np_grad = np.zeros((2,3))
for c in range(0, 2):
    for k in range(0, 3):
        for i in range(0, size-2):
            np_grad[c, k] += (np_res[c, i] - np_expected[c, i]) * np_input[i+k]
np_grad *= 1 / (size-2)

# Claude version:
N = np_res.size  # 2 * (size - 2)
diff = np_res - np_expected  # shape (2, size-2)

np_grad_c = np.zeros((2, 3))
for c in range(2):
    for k in range(3):
        np_grad_c[c, k] = (2.0 / N) * np.sum(diff[c, :] * np_input[k:k + (size - 2)])

print("grad:")
print(np_grad)
print("grad_c:")
print(np_grad_c)
assert np.allclose(np_grad, np_grad_c)
assert np_res.shape == (2, size-2)
assert np_grad.shape == (2, 3)


[[ 0.3994004  -0.09879403 -0.12640348  0.56344069 -0.17276651 -0.771467
  -0.09590877  0.67300121 -0.22495869  0.00833487 -0.23168219 -0.56188547
   0.42461203  0.73555668  0.31138141 -0.21260627 -0.63432484 -0.61301039]
 [ 0.54969299  0.12166152  0.64848702  0.24806499  0.08504633  0.4208315
   0.85651333  0.51674027  0.18351211  0.74169896  0.17517724  0.97338115
   0.73706271  0.54876912  0.00150603  0.23738772  0.2141123   0.87171256]]
grad:
[[-0.0823085  -0.22368503 -0.33027854]
 [ 0.01226582  0.05973139 -0.00302497]]
grad_c:
[[-0.0823085  -0.22368503 -0.33027854]
 [ 0.01226582  0.05973139 -0.00302497]]
